In [1]:
import numpy as np

In [15]:
np.random.seed(0)
A = np.random.randint(0,10,[5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

# Methodes ndarray

In [5]:
A.sum(axis=1)

array([ 8, 19])

In [6]:
A.argmin(axis=0)

array([1, 0, 0])

In [7]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

## Statistiques

In [8]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [9]:
A.mean()

4.5

In [10]:
A.std()

2.9297326385411577

In [11]:
A.var()

8.583333333333334

In [13]:
np.corrcoef(A)[0,1]

-0.563621480190678

In [17]:
values, counts = np.unique(A,return_counts=1)
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3])

In [19]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j} fois')

valeur 0 apparait 1 fois
valeur 2 apparait 1 fois
valeur 1 apparait 2 fois
valeur 4 apparait 2 fois
valeur 6 apparait 2 fois
valeur 3 apparait 3 fois
valeur 5 apparait 3 fois
valeur 9 apparait 3 fois
valeur 7 apparait 4 fois
valeur 8 apparait 4 fois


## NaN Corrections

In [22]:
A  = np.random.randn(5,5)
A[0,2] = np.nan
A[4,3] = np.nan
A

array([[ 0.17742614, -0.40178094,         nan,  0.46278226, -0.90729836],
       [ 0.0519454 ,  0.72909056,  0.12898291,  1.13940068, -1.23482582],
       [ 0.40234164, -0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244, -1.53624369],
       [ 1.48825219,  1.89588918,  1.17877957,         nan, -1.07075262]])

In [23]:
np.nanmean(A)

0.01371669980875766

In [25]:
np.isnan(A).sum()/A.size

0.08

In [28]:
A[np.isnan(A)] = 0
A

array([[ 0.17742614, -0.40178094,  0.        ,  0.46278226, -0.90729836],
       [ 0.0519454 ,  0.72909056,  0.12898291,  1.13940068, -1.23482582],
       [ 0.40234164, -0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244, -1.53624369],
       [ 1.48825219,  1.89588918,  1.17877957,  0.        , -1.07075262]])

In [29]:
A = np.ones((2,3))
B = np.ones((3,2))
A, B

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [30]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [32]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [33]:
A = np.random.randint(0,10,[3,3])
A

array([[9, 8, 0],
       [8, 5, 9],
       [0, 9, 6]])

In [34]:
np.linalg.det(A)

-843.0000000000007

In [35]:
np.linalg.pinv(A)

array([[ 0.06049822,  0.0569395 , -0.08540925],
       [ 0.0569395 , -0.06405694,  0.09608541],
       [-0.08540925,  0.09608541,  0.02253855]])

In [36]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-6.00902682,  7.63530216, 18.37372465]), eigenvectors=array([[ 0.39232879,  0.72347646,  0.56803162],
       [-0.73605917, -0.12341585,  0.66557151],
       [ 0.55162942, -0.67922775,  0.48410189]]))